### ISSUE TITLE
Improve the presentation of "multi-values" in DejaCode Reports

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#10]
Currently when we have a Report Query that returns a field with multiple values (for instance multiple tags for a license), they are presented as a list of values separated by commas such as in True, False, True, True
When two columns have similarly "aligned" values such as a license key, it is therefore hard to see which license has which tag:

```
Component License                Redistribution
ABC       apache-2.0,            False, False,
          mit, bsd,              False, True
          gpl-2.0
```

An alternative approach would be to separate each of the multi-values with a new line instead of a comma, enabling us to present a visual alignment of the values:

```
Component License                Redistribution
ABC       apache-2.0             False
          mit                    False
          bsd                    False
          gpl-2.0                True
```

Note that the solution is a bit complicated because of the multiple Report output formats supported: 
-  the DejaCode UI preview of the Report
- the export formats: doc, html, json, xls, xlsx (the default), and yaml. 

Any solution needs to work with all supported formats.

**Comment by tdruez** [comment]
Changes:

- "," replaced by new line for doc, html, xls, xlsx formats
- for json
```
"license__name": [
  "Apache License 2.0",
  "Apache License 1.1"
]
```
- for yaml
```
license__name:
    - Apache License 2.0
    - Apache License 1.1
```

**Comment by DennisClark** [comment]
@tdruez  I reviewed several impacted reports on staging starship.  It all looks good to me, thanks.

**Comment by tdruez** [comment]
Merged and deployed.
