### ISSUE TITLE
Add full purl to most screens

### ISSUE THREAD

**Issue by mjherzog** [nexB/dejacode#115]
DejaCode should display the full purl in the Product/Inventory, Packages and Product/Compare screens and possibly other DejaCode screens. My recollection is that we streamlined the display to type/namespace/name/version for simplicity but as we work more with Packages data (esp. from Linux or other distros) it is very important to be able to see the qualifier and subpath if present. 

This will make the screens more directly informative and make it much easier to compare Packages.

**Comment by tdruez** [comment]
See also https://github.com/nexB/dejacode/issues/18

**Comment by tdruez** [comment]
The full PURL including the "pkg:" prefix is now used everywhere in the DejaCode UI.

**Comment by DennisClark** [comment]
Updates confirmed, thanks @tdruez

**Comment by DennisClark** [comment]
@tdruez   The Packages list user view is showing the PURL, but the Qualifiers are not being displayed there.  Can you please investigate. Also, the Qualifiers are not being shown on the Product Inventory form.

**Comment by DennisClark** [comment]
@tdruez    Fixes confirmed in Staging Projects dataspace.  This time I tested all the purl fields.  Thanks very much!

**Comment by tdruez** [comment]
Fix deployed.
