### ISSUE TITLE
Add a Delete function to the Edit Product Relationship form 

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#128]
**Is your enhancement request related to a problem? Please describe.**
Cumbersome to delete an old version of a Package or Component from a Product Inventory.

**What are the benefits of the requested enhancement?**
Facilitate Product Inventory management, especially when adding new versions of existing items.

**Describe the solution you would like**
Add a Delete function to the Edit Product Relation (Package/Component) form (a button at the bottom).

**Comment by tdruez** [comment]
The "Delete" button was not properly migrated during the Inventory tab refactoring in https://github.com/nexB/dejacode/pull/24/files

Some permissions where not available in the tab context anymore and the button was hidden.
Fixed in https://github.com/nexB/dejacode/pull/134
