### ISSUE TITLE
Populate "package notice text" using NOTICE* files text

### ISSUE THREAD

**Issue by pombredanne** [nexB/dejacode#136]
We should do a better job to populate "package notice text" field of a Package using NOTICE* files text, and related key files notices that we detect.

See also:
- https://github.com/nexB/scancode-toolkit/issues/3511

**Comment by DennisClark** [comment]
please concatenate the texts if multiple "key" files are detected, with the NOTICE file first if there is one.

**Comment by tdruez** [comment]
Merged and deployed.
