### ISSUE TITLE
Cannot add npm package PURL with namespace

### ISSUE THREAD

**Issue by pombredanne** [nexB/dejacode#144]
Using the "Add Package" popup, I want to add a package with either this PURL `pkg:npm/@clayui/tooltip@3.1.0` or this encoded PURL `pkg:npm/%40clayui/tooltip@3.1.0`4
It fails with this message in all cases:
`Error: Could not download content: http://registry.npmjs.org/tooltip/-/tooltip-3.1.0.tgz `

Yet the package exists:
- https://www.npmjs.com/package/@clayui/tooltip/v/3.1.0?activeTab=versions

And the API URL and download would be:
- https://registry.npmjs.org/@clayui/tooltip/3.1.0
- https://registry.npmjs.org/@clayui/tooltip/-/tooltip-3.1.0.tgz

Note that if I try to create a package with:
- https://registry.npmjs.org/@clayui/tooltip/-/tooltip-3.1.0.tgz

it works

**Comment by pombredanne** [comment]
Since  I have a workaround by submitting the download URL this is not a blocker

**Comment by tdruez** [comment]
Fixed on the `packageurl-python` side at https://github.com/package-url/packageurl-python/pull/158

**Comment by tdruez** [comment]
Fix merged and deployed.
