### ISSUE TITLE
The "Add to Product" from the "Packages Import" is not working

### ISSUE THREAD

**Issue by chinyeungli** [nexB/dejacode#164]
i.e.
https://enterprise.dejacode.com/admin/component_catalog/package/import/
I imported the packages alright
Once it's imported, I clicked the "Add to Product" button at the bottom of the page and chose the product. The screen loaded for a second and then returned to the package list. However, when I checked the product, those packages weren't added.

**Comment by tdruez** [comment]
Fixed in https://github.com/nexB/dejacode/commit/0f01d2b4f79dbd92575ec51d3f21f29a4894a498
