### ISSUE TITLE
Product command "Check for new Package versions" simply returns "Error"

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#17]
The Product command "Check for new Package versions" simply returns "Error" in DejaCode 5.0.  I confirmed that this occurs even when all Integrations Statuses are configured and available. 

<img width="1447" alt="Check for new package versions error" src="https://github.com/nexB/dejacode/assets/4991620/217bdb04-5cc9-4964-8c46-8407bcd82615">

**Comment by DennisClark** [comment]
@tdruez   please investigate this one soon, thanks

**Comment by tdruez** [comment]
Problem solved in https://github.com/nexB/dejacode/pull/23

**Comment by DennisClark** [comment]
@tdruez    Thanks !
