### ISSUE TITLE
Support download of both ScanCode Summary and Details for a package scan

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#21]
While analyzing a Package in DejaCode recently created from https://github.com/VictoriaMetrics/VictoriaMetrics/archive/refs/tags/v1.93.9.tar.gz I used the `Download Scan data` button to get a copy of the scan results, and discovered that when I examined the downloaded file that there was no summary information in it, such as the license clarity scoring details.  I submitted the same package directly to ScanCode.io and discovered that it produces two scan results files, `summary-<timestamp>.json` and `scancode-<timestamp>.json` and that the summary file has the information that I needed.  

Currently the scan results page on Package only gives me the ability to download the scan result details.  I think we should improve that by either: 
* improving the existing button to download both files, OR
* providing 2 buttons `Download Scan summary` and `Download Scan details` 

The summary has a lot of information that is useful to the user wanting to know more about the Package.

**Comment by tdruez** [comment]
`Download Scan data` now returns a zip file containing both json files.
