### ISSUE TITLE
Enable bootstrap dark mode

### ISSUE THREAD

**Issue by tdruez** [nexB/dejacode#25]
https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode

**Comment by DennisClark** [comment]
@tdruez    in Staging nexB Dark mode looks great, but Auto mode is a bit strange.  See the attached screenshot, where the Global search field is hard to read in Auto mode, although it looks just fine in Light and Dark modes. 

<img width="1451" alt="DejaCode in Auto mode" src="https://github.com/nexB/dejacode/assets/4991620/ea172040-977c-4937-a858-bffc02eccca1">
