### ISSUE TITLE
adding {%csrf_token%}

### ISSUE THREAD

**Issue by jo780-full** [nexB/dejacode#27]
https://github.com/nexB/dejacode/blob/01cf3b09b944fa5385db6c84c8baf92a1557ea96/dje/templates/registration/login.html#L27
Hello , while setting up this repository, I noticed that this form does not have csrf_token which is required according to django documentation. Is this an error or is it by design cause , after adding this I was able to view my `/home/` tab

**Comment by tdruez** [comment]
@jo780-full The `csrf_token` should be included in the `{% crispy form %}` call, see https://github.com/nexB/dejacode/blob/01cf3b09b944fa5385db6c84c8baf92a1557ea96/dje/templates/registration/login.html#L28

The `<input type="hidden" name="csrfmiddlewaretoken" value="****">` input is properly rendered in the HTML source on my side, could you make sure it is missing in the source on your side?

**Comment by jo780-full** [comment]
Sure ill check, this

**Comment by jo780-full** [comment]
I needed to allow localhost as the origin for CSRF protection in Django and   adjusted the CSRF_TRUSTED_ORIGINS. sorry and thx

**Comment by tdruez** [comment]
No worries, thanks for reporting.

**Comment by jo780-full** [comment]
is there a channel i can communicate like slack or something ?

**Comment by tdruez** [comment]
Yes at https://app.gitter.im/#/room/#aboutcode-org_discuss:gitter.im
