### ISSUE TITLE
Add pagination on the Product Inventory tab

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#3]
We need to add add pagination on the Product Inventory tab, since the number of Inventory Items can easily be well over 100.   

Also, we need to fix the default ordering (which is currently based on `pk`) and provide sorting options (perhaps on the column headers).

**Comment by DennisClark** [comment]
@tdruez   Performance greatly improved!  
I found one small issue with the pagination: on Product DejaCode 5.0, when I do a "Check for new Package versions" I get zero results (that's ok) but when I click on the "Show All Items" link, it returns results for Page 1 but without the pagination controller that usually shows up in the upper right, so I have no way to get to Page 2 unless I use the Refresh Page feature of the browser (I'm using Firefox), and that works to restore the initial Inventory presentation.   That's the only problem I have found so far.

**Comment by DennisClark** [comment]
@tdruez  The Search Inventory field works quite well, and performs well, and appears to search the entire product inventory, which makes sense, but the results could be improved if it would show something like "nn of 882 results" rather than just "nn results".  Also, it would be very helpful to have some kind of "Show All" button after one does a search.

**Comment by DennisClark** [comment]
@tdruez  for the record, I was able to import an additional package into the Starship Product "A1" with no problems.  I found the package easily enough by searching on the name of the ScanCode.io output file that I used, `scancode-2023-11-11-15-47-55`.

**Comment by tdruez** [comment]
@DennisClark I've refined the display of the pagination element in the UI, the pagination links will appear when using the "Show All Items".
Also, the total count is now displayed as a "reset" link.

Now, about the "Check for new Package versions", I don't think the current implementation works that well in the context of the pagination. I'm not sure how useful it is to only get the updated information for the current page. I would prefer to rework this implementation as another ticket, returning the whole list of available updates, maybe in a new tab.
Let me know your thoughts.

**Comment by DennisClark** [comment]
@tdruez   thanks for the updates, I'll take a look shortly.  On further thought, I agree that you should probably rework the  "Check for new Package versions" implementation as another ticket, and that returning the whole list in another tab could be the best way to do it -- worth trying out anyway!

**Comment by DennisClark** [comment]
@tdruez   the total count "reset link" and the pagination controller are working very nicely.  

I did a "Check for new Package versions" and that worked fine, although I had to wait at least a minute on an Inventory with 882 items. I selected one of the suggested new Package versions, and got the PurlDB entry and created a Package in DejaCode for that, and then I added it to my Product.  It sorted the new Package right after the old one in the Product Inventory, as it should.  Then I figured I should delete the old one, and that turned out to be rather cumbersome.  I had to go to "Manage >> Packages", which does not use the improved sorting or pagination, and I could only find the Package I wanted to delete by doing an inventory search, which returned the correct results, and I was able to use the rather strange delete technique that is on the Manage Packages form to delete the old one.  So we have a somewhat awkward process flow problem: initial display is good, checking for new versions is good, adding the new Package is good, but then deleting the old one is challenging and non-intutuitve, although it finally did what I needed it to do.  Perhaps we could add a Delete function to the Edit Product Package form?  That would make the whole thing a lot easier, and we could address the Manage Packages UI issues later (or basically figure out what to do with the Manage forms altogether).

**Comment by tdruez** [comment]
@DennisClark The search and pagination for the inventory tab is now merged and deployed.

I'd like to close this issue but first I've added https://github.com/nexB/dejacode/issues/127 regarding the "Check for new Package versions" refinements.

Could you create a new issue from your comment at https://github.com/nexB/dejacode/issues/3#issuecomment-1866960049 since it's not directly related to the pagination implementation, I would prefer to handle it as it's own ticket.

**Comment by DennisClark** [comment]
@tdruez   new issue #128  created; please feel free to close this one.

**Comment by tdruez** [comment]
@DennisClark Thanks!

**Comment by mjherzog** [comment]
Looking good. Thanks.
