### ISSUE TITLE
Update links for DejaCode documentation

### ISSUE THREAD

**Issue by mjherzog** [nexB/dejacode#38]
Our primary DejaCode documentation is now at: https://dejacode.readthedocs.io/en/latest/, but there is no link to it from the DjC Home page.
- From Support the link is to https://nexb.com/resources/#support which then has a link to https://aboutcode.readthedocs.io/en/latest/aboutcode-project-overview.html for Docs. This should be changed to: https://dejacode.readthedocs.io/en/latest/. 
- Or we could have a direct link to the documentation from the Home Page menu.

**Comment by DennisClark** [comment]
See screenshot for Home page doc link. The label is "Tutorials" and it is much more than that of course; perhaps we can improve the label. 

I have also added a link in the green home page announcements box to various dataspaces, including the Public Evaluation home page. 

<img width="332" alt="Home Page Doc Link" src="https://github.com/nexB/dejacode/assets/4991620/d6975975-ddc9-4e93-8f5f-71956cc1d33f">

**Comment by mjherzog** [comment]
Thanks. I missed that hiding in plain sight because I was focused on the menu. We do need to improve the labeling and update the Support/Docs link to point to the real doc. Basically you should have access to the same doc links from the menu as from the Home page because you may not be on the Home page when you are looking for the documentation.

**Comment by DennisClark** [comment]
@tdruez   please update the Label `Tutorials:` currently on the DejaCode Home page to `Documentation:` and change the link to https://dejacode.readthedocs.io/en/latest/.  Also, we don't need the `New` highlight anymore. 

Also please add an option to the main DejaCode dropdown menu named `Documentation` with the link https://dejacode.readthedocs.io/en/latest/     
I think the best position for the new option would be just above the current `Support` option.  

On the other hand, I think the current `Support` option is fine to leave as is.

**Comment by tdruez** [comment]
@DennisClark I've applied your suggestion and added the `Documentation` in the footer as well for consistency with the header.

**Comment by DennisClark** [comment]
@tdruez   All improvements confirmed, thanks very much for the fast response!
