### ISSUE TITLE
The Admin "Activity Log" reports are ignoring the entered "Days of Activity".

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#39]
The Admin "Activity Log" reports are ignoring the entered "Days of Activity", and appear to always use the default of 90 days.

Also, the reports do not appear to be sorted in any logical order. The best sort order would be by "Action time" descending.

Example of an Owner Activity Log (which was requested to be for 30 days of activity) attached.

[owner_activity_log_20231129.html.zip](https://github.com/nexB/dejacode/files/14091062/owner_activity_log_20231129.html.zip)

**Comment by tdruez** [comment]
Fixed and deployed.
