### ISSUE TITLE
Provide ability to Import an ABOUT file into DejaCode

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#43]
See related issue #42 

DejaCode currently provides a simple and convenient interface that enables a user to generate an ABOUT file (and associated files) for a Package or Component; however, the direction is only outbound from DejaCode.

Consider enhancing DejaCode to support the ability to import an ABOUT file, with the result being either the creation of a new Package or updates to a Package already defined in DejaCode. 

- Note that the PURL of a DejaCode Package is (must be) exactly the same as the PURL in a corresponding ABOUT file (perhaps obvious but worth emphasizing). 
- It might also make sense for this proposed Import process to query the PurlDB to find and use any additional useful details that could be useful when creating a new Package, but are not provided in the ABOUT file being imported.

Once the import is completed, then the DejaCode user would be able to see all the Package details in the standard DejaCode details view, and also reproduced in the ABOUT tab.

**Comment by DennisClark** [comment]
Note that an ABOUT file "bundle" may include: 
- a .ABOUT file
- a .NOTICE file
- one or more .LICENSE file(s)

The .NOTICE file generally contains important details about a Package, especially regarding its copyright and license terms. The text of the .NOTICE file should be copied into a DejaCode Package definition when available.

**Comment by tdruez** [comment]
@DennisClark you can already import `.ABOUT` file into DejaCode using the "Load Packages from SBOMs" Product feature:

![Screenshot 2024-05-28 at 10 06 24](https://github.com/nexB/dejacode/assets/489057/1ebba129-c288-4c9b-ad95-026ab1f90df8)

Note that you can provide multiple `.ABOUT` files into a zip archive (along with any other supported SBOMs) or provide a single `.ABOUT` file.

Please have a look at the existing feature and let me know if anything else is needed.

**Comment by DennisClark** [comment]
@tdruez   thanks for pointing out the existing feature, which I have confirmed as working just fine.
