### ISSUE TITLE
Problems with the Filter dropdown on the DejaCode PurlDB view

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#44]
On the DejaCode PurlDB view, if I use the Filter dropdown and enter `gem` and click the Filter button (or simply press return), the application is updating the URL with all the possible Filter parameters like this

`https://public.dejacode.com/purldb/?type__iexact=gem&namespace__iexact=&name__iexact=&version__iexact=&download_url__iexact=&filename__iexact=&sha1=&md5=&size=&release_date=&purl=&q=&sort=`

which is not actually filtering by a type of `gem` and it continues to show all of the packages in the PurlDB.

**Comment by DennisClark** [comment]
Alternatively, I can manually modify the DejaCode URL like this

`https://public.dejacode.com/purldb/?type=gem`

and I get the expected 813,446 results.  So there must be something about the URL modifiers that the Filter button is generating that does not produce the desired results.

**Comment by tdruez** [comment]
@DennisClark Fixed and deployed for you to review.

**Comment by DennisClark** [comment]
@tdruez   Fix confirmed in DejaCode production (especially after I cleared my browser cache).   Thanks for the speedy resolution!
