### ISSUE TITLE
Make the assignment of Keywords in DejaCode more flexible

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#48]
We should use the ComponentKeyword as suggestions in the keyword autocomplete fields and remove the validation to allow any keywords values.

In DejaCode, at the moment, only keywords existing as ComponentKeyword in the Dataspace are allowed. This approach is not compatible with automatically adding arbitrary keywords from Scan results or other integration processes.

Background: Scan results from SCTK returns keywords such as:
```
wrapper
proxy
decorator
Development Status :: 5 - Production/Stable
Programming Language :: Python :: 2
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
Programming Language :: Python :: 3.7
Programming Language :: Python :: 3.8
Programming Language :: Python :: 3.9
Programming Language :: Python :: 3.10
Programming Language :: Python :: 3.11
Programming Language :: Python :: Implementation :: CPython
Programming Language :: Python :: Implementation :: PyPy
```

**Comment by DennisClark** [comment]
This issue transformed to https://github.com/nexB/dejacode/issues/48 
Closing this one.

**Comment by tdruez** [comment]
@DennisClark Keywords validation was relaxed to accept any values. The existing values in the database are use for the autocompelte suggestion.

**Comment by DennisClark** [comment]
@tdruez   wonderful, thanks
