### ISSUE TITLE
Enhancement request: add support to scan package manifest

### ISSUE THREAD

**Issue by pombredanne** [nexB/dejacode#65]
Following recent  changes in SCIO we no longer can import product's data from package manifest
- https://github.com/nexB/dejacode/issues/64

I would like to have the ability to simply upload a package manifest or lockfile as a product like in the former "import_manifest" feature.

We could do it best IMHO as two imports: `import SBOM` and  `import_manifest` that would other behave the same.

**Comment by DennisClark** [comment]
In addition to the current "Scan" dropdown options on a Product, how about a new one to

Import data from Package Manifest 

or better maybe

Interpret data from Package Manifest

<img width="299" alt="Screenshot 2024-03-18 at 10 19 05" src="https://github.com/nexB/dejacode/assets/4991620/c28d29fb-684b-4984-8990-636e2ecbf48c">

**Comment by tdruez** [comment]
We had "Import Packages from manifest" before the renaming to "Load Packages from SBOMs".

**Comment by DennisClark** [comment]
Perhaps we need to re-introduce "Import Packages from manifest"  then as a fifth option.

**Comment by pombredanne** [comment]
> Perhaps we need to re-introduce "Import Packages from manifest" then as a fifth option.

This sounds the sanest and I like the fact this is more explicit than trying to guess of we have SBOMs or manifests.

**Comment by DennisClark** [comment]
@tdruez testing on staging went reasonably well.  I submitted a request for the requirements.txt file from pi-hole-5.17.3 (attached) and it imported a number of packages, and also reported 3 errors, but the log does not tell me what those errors are.  See screenshots. 


[requirements.txt](https://github.com/nexB/dejacode/files/14697013/requirements.txt)

<img width="1451" alt="Screenshot 2024-03-21 at 07 55 36" src="https://github.com/nexB/dejacode/assets/4991620/192dcb09-eff8-4c16-9f32-d872e4943147">
<img width="786" alt="Screenshot 2024-03-21 at 08 00 29" src="https://github.com/nexB/dejacode/assets/4991620/1f8012df-8c91-47ee-b9e9-e006532eba55">

**Comment by tdruez** [comment]
@DennisClark The added objects and the errors are now listed in the sttatus modal.

**Comment by tdruez** [comment]
@DennisClark I've re-worked the implementation for objects available in reference Dataspace, those are now automatically copied from the reference instead of raising errors and forcing the manual copy. This should be more efficient on large imports.

**Comment by DennisClark** [comment]
@tdruez   Excellent enhancement, thanks!   On Staging Starship, my import worked fine with no errors, and the packages copied from reference data look good.  No problems found.
