### ISSUE TITLE
Enhance Product Compare to allow user to save the results

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#7]
The results of a DejaCode Product Compare can be very useful in the ongoing analysis and communication activities that happen during product SCA or the defining of a new product version.

It would be extremely helpful for the User to be able to save the results in Excel format. Other nice formats would be a Word document (where the results would be in a Word document table, if possible) and/or html and/or pdf. But the most important and useful output format would probably be Excel, in order to support analysis, editing, and annotation among product stakeholders. 

Note that there are some non-editable workarounds: 
- You can do a browser "Save Page As..." on the Product Comparison, and select "Web Page Complete" (or equivalent, depending on browser), which generates an html file, but with some formatting issues. 
- You can Print the Product Comparison using your browser, perhaps using the save-to-PDF option.

**Comment by DennisClark** [comment]
@tdruez   The download works nicely on staging starship.  I have one little suggest improvement:  perhaps the exported filename should contain the Product Name, since we are normally comparing two versions of the same Product.  For example, something like "CargoManager_product_comparison.xlsx" .

**Comment by DennisClark** [comment]
Product Review
If you select two versions of the same Product in the Product list, and click the Compare button, you can now download the results of the comparison to a .xlsx file, making it easy to share the information with your colleagues.

**Comment by tdruez** [comment]
>  I have one little suggested improvement: perhaps the exported filename should contain the Product Name

@DennisClark Since there are 2 products in the comparison, which one should be used in the output file name?

**Comment by DennisClark** [comment]
Ah, never mind about the output file name.  I have never compared two different products, just different product versions, but since we support any comparison (I just now tried it), trying to generate a predictable output file name is probably way too complicated.   In short, it's great the way it is now, thanks.
