### ISSUE TITLE
Enhancement request: provide hint in package tree navigation

### ISSUE THREAD

**Issue by silverhook** [nexB/dejacode#70]
**Is your enhancement request related to a problem? Please describe.**

When navigating through the hierarchy, it is not apparent which package/dep has further deps.

For example in the following screenshot all the packages seem the same.

![image](https://github.com/nexB/dejacode/assets/3227264/1c58fb03-b4da-453f-a5df-dbf2473a63cd)

But if you click on Qt, it clearly has several dependencies.

![image](https://github.com/nexB/dejacode/assets/3227264/5c2faa82-4410-4c03-a3c9-ebd475b50731)

**What are the benefits of the requested enhancement?**

It would make navigating the package hierarchy easier.

**Describe the solution you would like**

I think a visual indicator – e.g. a connector dot on the right-edge of the package bubble – would be enough.

**Comment by DennisClark** [comment]
@tdruez   This enhancement looks really good in Staging Starship.  I like the use of the dot to indicate that there is a link to more connections.  (and I am reminded to take a closer look at somewhat related issue #87 )

**Comment by tdruez** [comment]
PR merged and deployed.
