### ISSUE TITLE
BUG: Web does not start due to gunicorn parameters

### ISSUE THREAD

**Issue by stefan6419846** [nexB/dejacode#73]
**Describe the bug**

Following the installation docs, the `web` component will not start correctly, leading to a "Bad Gateway" error in nginx.

**To Reproduce**

1. Install Docker from the official Linux Mint Vera sources.
2. Follow the installation docs.
3. Observe `gunicorn: error: unrecognized arguments:  --workers 4`
4. Go to http://localhost and see an nginx error page.

**Expected behavior**

With the default parameter configuration/installation docs, the service should start cleanly.

**Context**

Removing the continuation backslash in https://github.com/nexB/dejacode/blob/024697b923b6e370d88b0decd5b045f746919262/docker-compose.yml#L33 seems to resolve the issue.

**Comment by pombredanne** [comment]
Thanks for the report. This is really weird.

**Comment by pombredanne** [comment]
@stefan6419846 could this be related to https://github.com/nexB/dejacode/issues/74 ?

**Comment by stefan6419846** [comment]
Thanks, this indeed seems to have fixed this issue.
