### ISSUE TITLE
DOC: `docker-compose` versus `docker compose`

### ISSUE THREAD

**Issue by stefan6419846** [nexB/dejacode#74]
The installation docs and the Makefile are using the `docker compose` command. This is unknown to the Docker version shipped on Ubuntu 22.04 (`Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`), which only knows `docker-compose`.

With this, the default installation and all Makefile commands will not work out of the box.

**Comment by stefan6419846** [comment]
Thanks for the hint - I have indeed been using the `docker-compose` package before and have not been aware that `docker-compose-v2` is indeed something to look out for (I have to admit that my Docker knowledge is rather limited). Installing the new package recognizes the command as expected.

**Comment by tdruez** [comment]
From https://docs.docker.com/compose/

> Docker's documentation refers to and describes Compose V2 functionality.
> Effective July 2023, Compose V1 stopped receiving updates and is no longer in new Docker Desktop releases. Compose V2 has replaced it and is now integrated into all current Docker Desktop versions. For more information, see Migrate to Compose V2.

We only offer support for Compose V2 in DejaCode.

> @pombredanne We need to fix this in the docs!

There is no mention of `$ docker-compose` (v1) in the docs, only references to `$ docker compose` (v2).

Closing.

**Comment by stefan6419846** [comment]
As mentioned before, my Docker knowledge is rather limited. I had an existing Docker installation on this device and out of memory used `docker-compose` after `docker compose` did not work (there are multiple installation methods and maybe this would depend on the method used) - never being aware that there has been a change at some point in time and there is indeed a new package. But everything is clear enough now and working as expected after the initial confusion.

**Comment by tdruez** [comment]
@stefan6419846 we have a warning about this in the ScanCode.io documentation, see https://scancodeio.readthedocs.io/en/latest/installation.html#build-the-image, but it was not added on the DejaCode side.
It may be useful to add it there as well.
