### ISSUE TITLE
BUG: Makefile proposes `createsuperuse`, which is undefined

### ISSUE THREAD

**Issue by stefan6419846** [nexB/dejacode#75]
**Describe the bug**

Using autocompletion for the Makefile commands, I am presented with `createsuperuse`, which is an undefined command.

**To Reproduce**

1. Type `make createsu` and hit the TAB key for auto-completion

**Expected behavior**

Only valid commands are proposed.

**Context**

https://github.com/nexB/dejacode/blob/024697b923b6e370d88b0decd5b045f746919262/Makefile#L167 misses the final `r`.

**Comment by pombredanne** [comment]
This is fixed. Thank you ++
