### ISSUE TITLE
BUG: User activation e-mails refer to support@dejacode.com

### ISSUE THREAD

**Issue by stefan6419846** [nexB/dejacode#76]
**Describe the bug**

After adding a new user, the corresponding e-mail contains a hardcoded reference to support@dejacode.com in case the activation link has expired. This does not make much sense for custom installations, as you probably will not be able to help with this without access to the instance.

**To Reproduce**

1. Create a new user.
2. Observe the logs of the `worker_1` Docker process.

**Expected behavior**

An instance-specific support address is provided.

**Context**

Template: https://github.com/nexB/dejacode/blob/main/dje/templates/django_registration/activation_email_body.txt I have not checked whether there are more cases with hard-coded addresses.

**Comment by tdruez** [comment]
@stefan6419846 Thanks for reporting this one. 
Fix implemented in https://github.com/nexB/dejacode/pull/80
See https://dejacode.readthedocs.io/en/latest/application-settings.html#dejacode-support-email for the new setting.
