### ISSUE TITLE
Display Inventory count on the Products list user view 

### ISSUE THREAD

**Issue by mjherzog** [nexB/dejacode#81]
The request is to add a column to the Product List display that shows the current Inventory count for the Product -  suggest between Status and Keywords fields.

When you are working with multiple data inputs for a Product (i.e. from SBOM imports from different SBOM producers) this will be very helpful to compare the results at a high level. My expectation is that this is a very easy change.

**Comment by tdruez** [comment]
@mjherzog New "Inventory" column added to the Product list.

**Comment by DennisClark** [comment]
updates confirmed, thanks @tdruez
