### ISSUE TITLE
Improve the UI presentation of individual PURL fields in the Package details user view

### ISSUE THREAD

**Issue by DennisClark** [nexB/dejacode#83]
Problem: It is challenging for a user to understand which fields of a PURL have been properly populated in a Package definition when viewing that Package in the details user view. Currently it is necessary to Edit the Package in order to see the individual PURL fields. 

Benefit: Better understanding of a Package PURL and its composition. 

Suggested solution: Enhance the Package details user view to show the individual PURL fields, in a manner equivalent to the way they are currently shown on the Edit form. 

Notes: This issue has become more urgent recently while analyzing the results of various package imports from different sources and customers.

**Comment by DennisClark** [comment]
Hi @tdruez   The new PURL fields look good in staging, and yes it is quite OK to show Qualifiers and Subpath only when at least one of them has a value.  

If possible, it would also be nice to provide balloon help text on each of the fields, although that is not critical.

**Comment by tdruez** [comment]
Inline help added and feature merged.
