### ISSUE TITLE
BUG: Column template with is_modified results in cells showing values for packages instead of one

### ISSUE THREAD

**Issue by rogu-beta** [nexB/dejacode#86]
**Describe the bug**
When creating a custom report with a column template of object type "Product Portfolio | product package relationship" and a column consisting of `product >> productinventoryitem > is_modified` then the resulting table will contain the `is_modified` for all packages in every cell of this column, instead of showing the value once for the respective package in the row.

**To Reproduce**
1. Create a column template through `/admin/reporting/columntemplate/add/`
    1. Set object type to `Product Portfolio | product package relationship`
    2. Add a column template assigned field: `product >> productinventoryitem > is_modified`
3. Create a report through `/admin/reporting/report/add/`
   1. Use the predefined "Product Package List (productpackage)" as query
   2. Use the newly created column template
4. Create a report

**Expected behavior**
The result of the report should show one value for `is_modified` per row, matching the property of the package in said row.

**Screenshots**
![2024-04-30-dejacode-column-template](https://github.com/nexB/dejacode/assets/157620768/9a36de94-ac93-4022-83a3-267a9818cad6)
![2024-04-30-dejacode-report-duplicate-entries](https://github.com/nexB/dejacode/assets/157620768/d47c374d-bd97-4c92-9bcb-4f5eadbb2190)

**Context (OS, Browser, Device, etc.):**
Not relevant

**Comment by tdruez** [comment]
@ghsa-retrieval Thanks for reporting this issue.
As a workaround, you can replace the column template assigned field: `package >> productinventoryitem > is_modified` by using directly `is_modified` without going through the `package >> productinventoryitem` relations.
