### ISSUE TITLE
Unclear description and support value for "keywords" field when doing "packages import"

### ISSUE THREAD

**Issue by chinyeungli** [nexB/dejacode#92]
When doing a "packages import", I got errors at some rows for the "keywords" field.
such as
```
admin
Select a valid choice. admin is not one of the available choices.

shells
Select a valid choice. shells is not one of the available choices.
```

However, the "keywords" field doesn't have any description or supported values documented when I expand the "Show/hide Supported Columns" at https://enterprise.dejacode.com/admin/component_catalog/package/import/#

It is unclear what are the supported value and the purpose of this field.

**Comment by tdruez** [comment]
@chinyeungli The `keywords` field was refactored to accept any values in https://github.com/nexB/dejacode/issues/48 and https://github.com/nexB/dejacode/pull/54
Also, I've added help text in the import view.
Thanks for reporting!
